// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2kD2XthGtXKCG8U42Tcha7
// Component: aUt5hf66GP
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import DashboardPanel from "../../DashboardPanel"; // plasmic-import: RFL4aeFfPU/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_resumen_gerencial.module.css"; // plasmic-import: 2kD2XthGtXKCG8U42Tcha7/projectcss
import sty from "./PlasmicDashboardPanelGroup.module.css"; // plasmic-import: aUt5hf66GP/css

export type PlasmicDashboardPanelGroup__VariantMembers = {};
export type PlasmicDashboardPanelGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboardPanelGroup__VariantsArgs;
export const PlasmicDashboardPanelGroup__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDashboardPanelGroup__ArgsType = {};
type ArgPropType = keyof PlasmicDashboardPanelGroup__ArgsType;
export const PlasmicDashboardPanelGroup__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboardPanelGroup__OverridesType = {
  dashboardPanelGroup?: p.Flex<"div">;
};

export interface DefaultDashboardPanelGroupProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicDashboardPanelGroup__RenderFunc(props: {
  variants: PlasmicDashboardPanelGroup__VariantsArgs;
  args: PlasmicDashboardPanelGroup__ArgsType;
  overrides: PlasmicDashboardPanelGroup__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"dashboardPanelGroup"}
      data-plasmic-override={overrides.dashboardPanelGroup}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.dashboardPanelGroup
      )}
    >
      <DashboardPanel
        className={classNames("__wab_instance", sty.dashboardPanel___2LFxn)}
      />

      <DashboardPanel
        className={classNames("__wab_instance", sty.dashboardPanel__pfoBt)}
        estado={"enTermino" as const}
        selected={true}
      />

      <DashboardPanel
        className={classNames("__wab_instance", sty.dashboardPanel__bq8N4)}
        estado={"atrasado" as const}
      />

      <DashboardPanel
        className={classNames("__wab_instance", sty.dashboardPanel___4RvN2)}
        estado={"suspendidos" as const}
      />

      <DashboardPanel
        className={classNames("__wab_instance", sty.dashboardPanel__jlqRz)}
        estado={"recaudado" as const}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dashboardPanelGroup: ["dashboardPanelGroup"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dashboardPanelGroup: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboardPanelGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboardPanelGroup__VariantsArgs;
    args?: PlasmicDashboardPanelGroup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDashboardPanelGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDashboardPanelGroup__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDashboardPanelGroup__ArgProps,
          internalVariantPropNames: PlasmicDashboardPanelGroup__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDashboardPanelGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dashboardPanelGroup") {
    func.displayName = "PlasmicDashboardPanelGroup";
  } else {
    func.displayName = `PlasmicDashboardPanelGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicDashboardPanelGroup = Object.assign(
  // Top-level PlasmicDashboardPanelGroup renders the root element
  makeNodeComponent("dashboardPanelGroup"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDashboardPanelGroup
    internalVariantProps: PlasmicDashboardPanelGroup__VariantProps,
    internalArgProps: PlasmicDashboardPanelGroup__ArgProps
  }
);

export default PlasmicDashboardPanelGroup;
/* prettier-ignore-end */
